CREATE database mobee;

use mobee;

CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    NOMBRE VARCHAR(350) NOT NULL,
    CORREO VARCHAR(350) NOT NULL,
    CONTRASENA VARCHAR(350) NOT NULL
);

CREATE TABLE FAVORITO_PELI (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    NOMBRE VARCHAR(350) NOT NULL,
    ID_PELICULA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE LISTA_PELI(
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    NOMBRE VARCHAR(350) NOT NULL,
    ID_PELICULA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE FAVORITO_SERIE (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    NOMBRE VARCHAR(350) NOT NULL,
    ID_SERIE INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE LISTA_SERIE(
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    NOMBRE VARCHAR(350) NOT NULL,
    ID_SERIE INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE PARATI_PELICULA (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    ID_PELICULA INT NOT NULL,
    POSTER VARCHAR(350),
    TITULO VARCHAR(350),
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE PARATI_SERIE(
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    ID_PELICULA INT NOT NULL,
    POSTER VARCHAR(350),
    NOMBRE VARCHAR(350),
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);


--------IMPLEMENTACIÓN DE LISTA DE AMIGOS----------




