CREATE database mobee;

use mobee;

CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    NOMBRE VARCHAR(350) UNIQUE NOT NULL,
    CORREO VARCHAR(350) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(350) NOT NULL
);

CREATE TABLE FAVORITOS(
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    NOMBRE VARCHAR(350) NOT NULL,
    TIPO VARCHAR(1) NOT NULL,
    ID_MULTIMEDIA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE LISTA(
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    NOMBRE VARCHAR(350) NOT NULL,
    TIPO VARCHAR(1) NOT NULL,
    ID_MULTIMEDIA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

--------IMPLEMENTACIÓN DE LISTA DE AMIGOS----------




